export const types = [
  'Lampe',
  'Kühlschrank',
  'Waschmaschine',
  'Steckdose',
  'Schalter',
  'Knöpfe',
  'Thermostat',
  'Stromzähler',
  'Bewegungsmelder',
  'Kameras',
  'Schließkontakte',
  'Fernseher',
  'Türklingel',
  'Steuerungseinheiten',
  "Bewässerung",
  'Sonstiges',
];
